[package]
name = "liboffsetup"
version = "0.0.1"
authors = ["Samuel Marks @SamuelMarks"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
config = "0.9.2"
http = "0.1"
structopt = "0.2.15"
serde = { version = "1.0.90", features = ["derive"] }